"use client"
import Provider from '@/components/Provider'
import './globals.css'
import { Inter } from 'next/font/google'
import { QueryClient, QueryClientProvider } from 'react-query'
import NavBar from '@/components/NavBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <Provider>
          <body className={`bg-zinc-700 ${inter.className}`}>
            <NavBar/>
            {children}
          </body>
      </Provider>
    </QueryClientProvider>
    </html>
  )
}
